### ISSUE TITLE
How do we use this with nuxt? 

### ISSUE THREAD

**Issue by Krislunde** [danielroe/beasties#45]
After installing, when adding to nuxt.config.js 

```
modules: [
		'beasties'
	],
```
I end up with the error 

`Class constructor Beasties cannot be invoked without 'new'    `

**Comment by vuthanhbayit** [comment]
use https://github.com/nuxt-modules/critters

**Comment by Krislunde** [comment]
> use https://github.com/nuxt-modules/critters

Thanks, I was, and came here because a terminal message during upgrade told me to use this going forwards.

**Comment by danielroe** [comment]
oops - my mistake

it’s migrated to use beasties but needs a release

**Comment by danielroe** [comment]
this should now be released
